using System;
using System.Collections.Generic;
using System.Linq;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace AvaloqDocu.Enums
{
    public enum FunctionalAreaEnum
    {
        [Display(Name = "-------- Avaloq Banking System --------")]
        AvaloqBankSys = 1,
        [Display(Name = "Accounting & Position Keeping")]
        AccPosKeeping = 2,
        [Display(Name = "AFP Front Office")]
        AFPFrontOffice = 3,
        [Display(Name = "AFP Mobile")]
        AFPMobile = 4,
        [Display(Name = "AFP Web Banking")]
        AFPWebBanking = 5,
        [Display(Name = "Application Management")]
        AppManagement = 6,
        [Display(Name = "Avaloq Front Platform")]
        AvaloqFrontPlat = 7,
        [Display(Name = "Backoffice Portal")]
        BackOfficePortal = 8,
        [Display(Name = "Business Bus")]
        BusinessBus = 9,
        [Display(Name = "Cashier Operations")]
        CashOperations = 10,
        [Display(Name = "Client Processes")]
        ClientProcess = 11,
        [Display(Name = "Collateral Management")]
        CollatManage = 12,
        [Display(Name = "Corporate Actions")]
        CorpActions = 13,
        [Display(Name = "Costs & Fees")]
        CostsFees = 14,
        [Display(Name = "Credit Initiation & Processing")]
        CredInitProc = 15,
        [Display(Name = "Credit Loans & Securities")]
        CredLoanSec = 16,
        [Display(Name = "Credit Risk Engine")]
        CredRiskEngine = 17,
        [Display(Name = "CRM")]
        CRM = 18,
        [Display(Name = "Financial Instruments")]
        FinInstrum = 19,
        [Display(Name = "Forex Feed & Calculation")]
        ForexFeedCalc = 20,
        [Display(Name = "Forex Management")]
        ForexMan = 21,
        [Display(Name = "Frontend")]
        Frontent = 22,
        [Display(Name = "Fund Saving Plan")]
        FundSavPlan = 23,
        [Display(Name = "Information Lifecycle Management")]
        InfLifeManage = 24,
        [Display(Name = "Installation Management")]
        InstManage = 25,
        [Display(Name = "Installer")]
        InstallerBS = 26,
        [Display(Name = "Interest")]
        Interest = 27,
        [Display(Name = "Islamic Banking")]
        IslamicBank = 28,
        [Display(Name = "Legal & Compliance")]
        LegalComp = 29,
        [Display(Name = "Message Engine")]
        MessageEng = 30,
        [Display(Name = "Migration Tools")]
        MigTools = 31,
        [Display(Name = "Money Market")]
        MoneyMarket = 32,
        [Display(Name = "Object Model & Static Data")]
        ObjModelStatData = 33,
        [Display(Name = "OTC Derivative")]
        OTCDeriv = 34,
        [Display(Name = "Output Management")]
        OutManage = 35,
        [Display(Name = "Parameterisation Tools")]
        ParamTools = 36,
        [Display(Name = "Payment")]
        Payment = 37,
        [Display(Name = "Physical Securities")]
        PhySecure = 38,
        [Display(Name = "Portfolio Management")]
        PortfoManage = 39,
        [Display(Name = "Reconciliation")]
        Reconciliation = 40,
        [Display(Name = "REPO")]
        REPO = 41,
        [Display(Name = "Report Engine")]
        ReportEngine = 42,
        [Display(Name = "Script Engine")]
        ScriptEngine = 43,
        [Display(Name = "Securities Trading")]
        SecureTrad = 44,
        [Display(Name = "Security")]
        Security = 45,
        [Display(Name = "Sensitive Data Separation")]
        SensDataSep = 46,
        [Display(Name = "Settlement")]
        Settlement = 47,
        [Display(Name = "SLB")]
        SLB = 48,
        [Display(Name = "Solution Model Development")]
        SolModelDevBS = 49,
        [Display(Name = "System Performance")]
        SysPerform = 50,
        [Display(Name = "Taxes")]
        Taxes = 51,
        [Display(Name = "Technical Kernel")]
        TechKernal = 52,
        [Display(Name = "Test Tools")]
        TestTools = 53,
        [Display(Name = "Trading & Risk Management")]
        TradRiskMgmt = 54,
        [Display(Name = "Treasury & Cash Management")]
        TreasCashMgmt = 55,
        [Display(Name = "Wealth Advisory")]
        WealthAdvisory = 56,
        [Display(Name = "Workflow & Order Processing")]
        WorkOrderProc = 57,
        [Display(Name = "-------- Avaloq Tools --------")]
        AvaloqTools = 58,
        [Display(Name = "Database Automation & Integration")]
        DataAutoInteg = 59,
        [Display(Name = "Delivery")]
        Delivery = 60,
        [Display(Name = "ice Workbench")]
        IceWorkbench = 61,
        [Display(Name = "Installer")]
        InstallerAT = 62,
        [Display(Name = "Naster Data Management")]
        MastDataMgmt = 63,
        [Display(Name = "Solution Model Development")]
        SolModelDevAT = 64,
        [Display(Name = "Support & Change Management")]
        SuppChangeMgmt = 65
    }
}