// <auto-generated />
namespace AvaloqDocu.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class documentmodelchanges : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(documentmodelchanges));
        
        string IMigrationMetadata.Id
        {
            get { return "201703082139259_document-model-changes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
